### ISSUE TITLE
Schema to setup project

### ISSUE THREAD

**Issue by slowas** [terrafirma2021/Yamaha-DataLogger#1]
Hey, I' am very intresting in your project can' you share schematic to setup this code?

**Comment by terrafirma2021** [comment]
Hi yes, I will make a schematic soon, I am currently finishing up on my code. 

I intend to rewrite the code to support a USB KKL Cable, (which I started from) meaning that any device with a USB host will natively be able to work from the KKL cable. This will help others who may not be able to solder, to plug in a cable :)

**Comment by terrafirma2021** [comment]
@slowas Please see my main repo,, i have attached a wokwi schematic with colour coding for you. Here is the URL to the Wowki design, please be aware that I have adjusted the pinout order for clear understanding. When you build your own design, only cross over the data lines once!
https://wokwi.com/projects/391712730296045569
